### ISSUE TITLE
Use of @peculiar/webcrypto in Auto-DAG-Data not defined in package.json

### ISSUE THREAD

**Issue by marc-aurele-besner** [autonomys/auto-sdk#173]
## Use of @peculiar/webcrypto in Auto-DAG-Data not defined in package.json

Auto-DAG-Data use `@peculiar/webcrypto` package, but this package is not defined in package.json

This error was likely not detected as Auto-ID does import this package, therefore the monorepo has access to it. But if using the auto-dag-data by itself, this creates a missing dependency error.

**Comment by clostao** [comment]
Yes, I detected this one yesterday. Thanks for your PR
