### ISSUE TITLE
Make UploadFileOptions for uploadFile, uploadFileFromInput and uploadFileFromFilepath optional

### ISSUE THREAD

**Issue by marc-aurele-besner** [autonomys/auto-sdk#197]
## Make UploadFileOptions for uploadFile, uploadFileFromInput and uploadFileFromFilepath optional

The 3rd parameter UploadFileOptions for uploadFiles related function should be optional as per we assume per default user don't want to encrypt or compress everything

**Comment by clostao** [comment]
I'd say that compressing files would be better to be the default config. Given compressing metadata is included in the head IPLD node of the file and file reconstruction is to be done by ourselves (through either our SDK or directly in the gateway) I'd prioritise to reduce the burden of the DSN.

**Comment by marc-aurele-besner** [comment]
Compressing as default or not, personally I'm not really opiniated on that, then we could pass in a default value for that 3rd parameter with the compression true, because atm

```typescript
type UploadFileOptions = {
  password?: string
  compression?: boolean
}
```
Has 2 parameters that are both optional, but that parameter is not optional and has no default, meaning the user need to at least pass a empty object to the function, and that make it look weird.

**Comment by clostao** [comment]
This was solved
