### ISSUE TITLE
Implement Support for Auto Score

### ISSUE THREAD

**Issue by jfrank-summit** [autonomys/auto-sdk#94]
The primary support for the Auto Score framework will be the implementation of verifiable credential issuance. Details to be found in [Claims Framework](https://www.notion.so/subspacelabs/Claims-Framework-8aab609a45f940b8acf35886282487bd) and [LetsID — Auto Score](https://www.notion.so/LetsID-Auto-Score-e3b9520a9f4345789c69d3f5a61c6ae5?pvs=21) Notion pages

**Comment by clostao** [comment]
Merged at https://github.com/autonomys/auto-sdk/pull/99
